### ISSUE TITLE
DNS doesn't work in the selective mode

### ISSUE THREAD

**Issue by alexx7311** [AdguardTeam/AdGuardVPNExtension#101]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

2.0.5 beta

### Environment

```markdown
- OS: Windows 11
- Browser: Chrome 114
```

### Issue Details

Preconditions:

You're logged in VPN extension. VPN is connected in General mode.

STR:
1. Go to AdGuard popup > Settings > DNS server and choose "Default"
3. Go to https://adguard.app/en/test.html and look at the DNS test results > Should be “Non-filtering” AdGuard DNS
4. Open context menu > AdGuard VPN > Selective mode
5. Open context menu > AdGuard VPN > Enable VPN on this website
6. Refresh the page and look at the DNS test results

<details>
  <summary>General</summary>

  ![General](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/114913601/f468bd23-3f9c-4403-92ba-9a518fcf8127)

</details>

<details>
  <summary>Selective</summary>

  ![Selective](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/114913601/cc2f6e3e-98c0-414f-8394-8182b924fafa)

</details>

### Expected Behavior

“Non-filtering” AdGuard DNS should be displayed.

**Comment by maximtop** [comment]
This issue comes up because AdGuard is reaching out to domains that aren't on the exclusion list. By adding those domains to the list, everything should run smoothly.
