### ISSUE TITLE
 Problem with authorization through IOS account

### ISSUE THREAD

**Issue by ijk777** [AdguardTeam/AdGuardVPNExtension#108]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

2.0.16

### Environment

```markdown
- OS:Windows 11
- Browser: Google Chrome Version 114.0.5735.199 (Official Build) (64-bit)
```

### Issue Details

I'm trying to login through the Apple ecosystem, and I get an error after entering the login / password on the Apple authorization page:

error="invalid_grant", error_description="Invalid redirect: https://auth.miniature-interactive-mesh.org/oauth.html?adguard-vpn=1 does not match one of the registered values."

**Comment by ameshkov** [comment]
Thank you for reporting it, it'll be taken care of soon.

This is a sever-side issue so closing it here.
