### ISSUE TITLE
Requires username and password to access the site

### ISSUE THREAD

**Issue by MaximusPanin** [AdguardTeam/AdGuardVPNExtension#111]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

2.0.16

### Environment

```markdown
- OS: Win10 x64
- Browser: Cent Browser 5.0.1002.354
```

### Issue Details

The third day, after enabling the plugin and trying to access any site through vpn, it asks for a login and password in a pop-up window.

### Screenshots

![2023-7-14 0-21-14](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/24373505/33b09138-a866-474f-af45-ea06db5d99d1)

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardVPNExtension/issues/110
