### ISSUE TITLE
Проблема с подключением

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdGuardVPNExtension#113]
```markdown
Версия браузера CentBrowser 5.0.1002.354
```

### Issue Details

Давно пользовался расширением проблем не было, но в последний месяц примерно, начало требовать логин пароль при попытке загрузить сайт с включенным расширением. В другом браузере Проверил проблемы нет. Но и в этом никогда не было, просто внезапно почему-то это случилось. Переустановка расширения не помогла.

### Screenshots

![image](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/19754243/2c398ef0-4b3a-4eda-a065-0b93c60451b4)

**Comment by Birbber** [comment]
@Smorvel Приветствую! Это известная проблема хромиум браузеров. Мы уже оттправили [баг репорт](https://bugs.chromium.org/p/chromium/issues/detail?id=1448133) по этой проблеме, но он ещё не был рассмотрен. 
К сожалению, мы никак не можем повлиять на появление данного всплывающего окна, поэтому необходимо ожидать исправлений со стороны Chromium.
Я закрою эту задачу. За прогрессом решения проблемы можете следить по ссылке, указанной выше.
