### ISSUE TITLE
Pings are recalculated too often, on every service worker restart

### ISSUE THREAD

**Issue by BOR-LAND** [AdguardTeam/AdGuardVPNExtension#120]
### Issue Details

AdGuardVPNExtension пингует все свои локации каждые 5 минут. Зачем так часто? Я спрашиваю как пользователь, который пользуется лишь одной локацией и видит кучу бесполезных запросов расширения.

### Proposed solution

Возможно стоит пинговать локации непосредственно при выборе-смене локации?

**Comment by maximtop** [comment]
Спасибо, мы поправим.
Сейчас по логике расширение пингует при открытии попапа, если предыдущий пинг был больше 10 минут назад, но из-за того что сервис воркере перезагружается раз в 5 минут, расширение пингует на каждый рестарт
