### ISSUE TITLE
If you signed up with a Google account using "Continue with Google" you can't delete the account

### ISSUE THREAD

**Issue by TNTBOMBOM** [AdguardTeam/AdGuardVPNExtension#122]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed
- [X] I checked the documentation and found no answer

### AdGuard VPN Browser Extension version

NA

### Environment

```markdown
- OS:Debian
- Browser: Chrome
```

### Issue Details

If I try to delete the account, it will ask me for a password. However, I didn't sign up using a password, so I believe this is a bug.

### Expected Behavior

Able to delete account.

### Screenshots

NA

### Additional Information

NA

**Comment by maximtop** [comment]
Hi @TNTBOMBOM,

Thank you for reporting this issue. Since you signed up with Google, you may not have a password set for your account. Here's what you can do:

1. **Set a Password**: Go to your account settings and set a password.
2. **Delete the Account**: With the password set, you should be able to delete your account as usual.

**Comment by TNTBOMBOM** [comment]
> Set a Password: Go to your account settings and set a password.

This statement doesn't exist. Here is what does exist:

_**Press on "Change password":**_ 

![pass](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/11895339/8c423f43-dd80-474f-8352-7740e36d0c57)

_**There is no current password:**_

![pass2](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/11895339/81df676d-66ea-431e-9159-b65e67f2abe8)

**Comment by maximtop** [comment]
I see. Log out, then specify your Google account email, try to log in via email, and press 'Forget Password.' This way, you'll be able to set a new password.

**Comment by TNTBOMBOM** [comment]
Okay, thanks for the help. It's working now, but it's still very difficult and could be simplified.
