### ISSUE TITLE
Auto connect to VPN on browser launch doesn't work

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNExtension#127]
### Issue Details

Every time you launch or restart the browser, you need to manually connect to the VPN in the extension, which is inconvenient.

### Proposed solution

Add the ability to auto connect to VPN when the browser launch.

**Comment by alexx7311** [comment]
@rakleed We have this feature already. 
Please open the popup > Settings and make sure 'Last used location' is selected in the Quick connect option.

**Comment by alexx7311** [comment]
@rakleed Please check if the problem reproduces on the latest release version.

**Comment by alexx7311** [comment]
@rakleed We'll close the issue for now. If the problem reoccurs, please reopen the issue.
