### ISSUE TITLE
In `README`, logo is hard to see when using dark theme in GitHub

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNExtension#133]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

N/A

### Environment

```markdown
- OS: N/A
- Browser: N/A
```

### Issue Details

In the https://github.com/AdguardTeam/AdGuardVPNExtension/blob/master/README.md, the logo is hard to see when using the dark theme on GitHub.

### Expected Behavior

You need to add a logo option for the dark theme. I wanted to do it myself by taking [this dark theme logo](https://github.com/AdguardTeam/AdGuardVPNExtension/blob/63d72c1dace95f4a332e2c350ad6b7ddf027a93d/src/assets/images/logo-vpn-dark.svg), but it doesn't have mentions to which platform the repository belongs, which is in the current logo.

Useful link: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/19418601/49c1bb32-6ed5-43d6-9091-c66325a5d1e2)

</details>

**Comment by rakleed** [comment]
@alexx7311 @maximtop @Birbber @slavaleleka you didn't add screenshots for the dark theme.

**Comment by alexx7311** [comment]
@rakleed Hello! We've updated logo and screenshots for both themes. Please take a look
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/114913601/9c48ef56-3e33-4a38-8179-73be7a7c38ab)

</details>

<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/114913601/a9ae39dd-86e6-4222-ab7b-f3caa161d031)

</details>

**Comment by rakleed** [comment]
@alexx7311 your screenshots in light and dark themes are the same. This is what the extension looks like with a dark theme:
![CleanShot 2023-10-27 at 20 03 32](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/19418601/b40a918b-6198-43fb-9a04-40a634a87d0b)
