### ISSUE TITLE
Add optional connection obfuscation

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNExtension#139]
### Issue Details

Nowadays it is often not possible to connect to your servers from Russia.

### Proposed solution

If possible, add optional connection obfuscation, such as V2Ray or Xray or Shadowsocks.

**Comment by ameshkov** [comment]
See my response here: https://github.com/AdguardTeam/AdGuardVPNForMac/issues/259#issuecomment-1717082122

**Comment by rakleed** [comment]
@ameshkov but the extension does not use your VPN protocol at all, but is used as a proxy, as far as I understand. Is it possible to add obfuscation here?

**Comment by ameshkov** [comment]
@rakleed we're very limited in what can be changed in the extension, it's all managed by the browser itself.
