### ISSUE TITLE
AdGuard VPN browser extension doesn't work in Russia

### ISSUE THREAD

**Issue by Dameron33** [AdguardTeam/AdGuardVPNExtension#148]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

2.1.8 (1033)

### Environment

```markdown
- OS:Windows
- Browser:Chrome
```

### Issue Details

Сегодня купил  подписку на месяц на этот VPN . Но этот Vpn не работает вообще, ни через браузер , ни через приложение.
Перепробовал все, пожалуйста верните деньги.

### Expected Behavior

Возврат денег

**Comment by alexx7311** [comment]
Проблема связана с недавними блокировками. К сожалению, на данный момент расширение для браузера в России
 будет очень нестабильно работать (если вообще будет работать), поэтому мы рекомендуем скачать **полноценное приложение AdGuard VPN**, которое должно работать.
 
Вот список того, что можно сделать, на случай проблем с приложением:
 
- Проверить обновления вручную, установить их. Если обновлений не находит, попробуйте немного позже. 
- Помимо этого, пробуйте другие локации (сервера), а в настройках AdGuard VPN измените DNS сервер с системного на любой другой из списка.
- Пользователям AdGuard VPN на мобильных устройствах Apple рекомендуем переключить приложение в Основной режим.
- Перезапускать приложение и проверять доступность сервиса, а также следить за новостями в группе: https://t.me/s/adguardru
 
@Dameron33 По вопросам возврата средств обратитесь, пожалуйста, в нашу службу поддержки support@adguard.com

**Comment by CatNightRU** [comment]
Приложение, к сожалению, сейчас тоже не работает
