### ISSUE TITLE
Adguard VPN extension not working with trend micro maximum security on edge

### ISSUE THREAD

**Issue by githubuser013** [AdguardTeam/AdGuardVPNExtension#15]
As the title says Adguard VPN extension not working with trend micro maximum security on edge correctly, all the servers appaired to be offline all the time, plus login issue.

Adguard VPN extension : 0.12.14
Trend micro maximum security : 17.7.1130
Microsoft edge : 95.0.1020.44
Windows 11

**Comment by ameshkov** [comment]
I am almost sure this should be reported to Trend Micro, there's nothing we can do on our side.

**Comment by githubuser013** [comment]
Thanks, I reported to trend micro, Lets see what happens.
