### ISSUE TITLE
The extension won't work, keeps asking to contact support

### ISSUE THREAD

**Issue by MXanadu** [AdguardTeam/AdGuardVPNExtension#157]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

Version2.1.5

### Environment

```markdown
- OS: Windows 11
- Browser: Microsoft Edge
```

### Issue Details

When i click on the VPN extension, it keeps loading infinitely and then an error message pops up asking to contact support.
![Screenshot 2023-12-19 112049](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/154315152/54bdb642-7730-4ae6-95dd-0fa24fd6772f)

**Comment by alexx7311** [comment]
@MXanadu Hello! Please try updating the extension to the latest version and see if the problem persists. Can you please specify which country you are in at the moment?

**Comment by LingamYoni** [comment]
I have the same issue with latest v2.1.7:
![изображение](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/40486018/2ede7be8-e1e7-4126-9a6b-d9f64fe4f024)
Microsoft Edge Версия 120.0.2210.91 (Официальная сборка) (64-разрядная версия) @ Windows 10 Pro

**Comment by AlSavIg** [comment]
Same issue in Yandex Browser 23.11.3.935 (64-bit), latest version of the extension (installed from chrome webstore), Russia, Win10
![image](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/56115945/e04cdfba-30d9-46af-b63c-a24b0c9b874e)

**Comment by alexx7311** [comment]
Dup. of https://github.com/AdguardTeam/AdGuardVPNExtension/issues/148
