### ISSUE TITLE
The extension won't work in Yandex browser

### ISSUE THREAD

**Issue by Alexarchey** [AdguardTeam/AdGuardVPNExtension#158]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

2.1.5

### Environment

```markdown
- OS: Windows 11
- Browser: Yandex Browser Build 23.11.2.771 (64-bit)
```

### Issue Details

The extension won't work

### Screenshots

![Снимок экрана 2023-12-20 204436](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/154460453/c085d88c-453d-4d47-988f-2d09f63f253f)

**Comment by alexx7311** [comment]
@Alexarchey Здравствуйте! В связи с недавними блокировками расширение может работать нестабильно на территории РФ. Попробуйте, пожалуйста, обновить версию расширения до актуальной. Если не поможет, то мы рекомендуем установить полноценное [приложение для Windows](https://adguardvpn-help.com/).

Закрываем, как дубликат https://github.com/AdguardTeam/AdGuardVPNExtension/issues/148
