### ISSUE TITLE
AdGuard VPN extension doesn't work in Russia

### ISSUE THREAD

**Issue by kirilltrofim** [AdguardTeam/AdGuardVPNExtension#159]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

AdGuard VPN Версия 2.1.5

### Environment

```markdown
- OS: Выпуск	
Windows 11 Pro
Версия	23H2
Дата установки	‎19.‎12.‎2023
Сборка ОС	22631.2861
Взаимодействие	Windows Feature Experience Pack 1000.22681.1000.0

- Browser:
Microsoft Edge
Версия 120.0.2210.77 (Официальная сборка) (64-разрядная версия)
Также не работает и в Яндекс Браузер и в Google Crome
```

### Issue Details

Не работает вообще расширение.

Нахожусь в РФ.

### Actual Behavior

Как только я зашел под своим аккаунтом перестало работать расширение вообще.
Выходит ошибка :
Произошла ошибка
Пожалуйста, свяжитесь с нами, если вы продолжаете видеть это сообщение

### Expected Behavior

Ожидал работу расширения.

### Screenshots

![Снимок экрана 2023-12-20 224804](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/47715866/c4e67595-3282-46f2-8ba8-05e3198e4321)

**Comment by alexx7311** [comment]
@kirilltrofim Здравствуйте! Расширение сейчас очень нестабильно работает в РФ, что связано с недавними блокировками. Попробуйте, пожалуйста, обновить версию до актуальной. Если не поможет, то мы рекомендуем установить полноценное [приложение для Windows](https://adguardvpn-help.com/).

**Comment by alexx7311** [comment]
Закрываем, как дубликат https://github.com/AdguardTeam/AdGuardVPNExtension/issues/148
