### ISSUE TITLE
Streamlare.com - Error

### ISSUE THREAD

**Issue by furt555nv** [AdguardTeam/AdGuardVPNExtension#16]
Not specific web site issue. This problem is also exist on other video hosting sites. I have already reported them to you before. Your VPN product is breaking some hosting sites.

Steps o reproduce:

- Install AdGuard VPN and add whitelist to the Streamlare
- If you click the Play button an error is displayed.

---

- Turn off AdGuard VPN from `chrome://extensions` tab. Or remove the site from the whitelist.
- Refresh the page and click play. The video starts playing.

```
VPN settings:

Mode: Regular
WebRTC - off
DNS - default
Version: 0.12.21
```
```
System:
Chrome 96
Win 10
```

https://streamlare.com/e/4RLg7lXM5eJn2QAe

<details><summary>Screenshot</summary>

 
![h1](https://user-images.githubusercontent.com/74098460/145122344-3c2cdbc2-8d34-49e4-9bef-4e3c0813fa2b.png)

</details>

**Comment by Birbber** [comment]
@furt555nv Hi! We couldn't reproduce the issue on our end. 
Could you check if there are any errors in console? Please show us the screenshot.

**Comment by furt555nv** [comment]
I closed this because you said it wasn't reproduced.
Thank you for your help
