### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by icorneli** [AdguardTeam/AdGuardVPNExtension#164]
### Issue Details

Is there any way to connect AdGuard VPN on Linux? *In addition to the extension which does not work and the router.

**Comment by icorneli** [comment]
> ### Issue Details
> Is there any way to connect AdGuard VPN on Linux? *In addition to the extension which does not work and the router.
> 
> ### Proposed solution
> _No response_
> 
> ### Alternative solution
> _No response_

The extension in the Russian Federation does not work.
The router option is not considered.

**Comment by zzebrum** [comment]
@icorneli CLI is under development, but no ETA has been given yet.
