### ISSUE TITLE
The extension isn't launching

### ISSUE THREAD

**Issue by BabiiIn** [AdguardTeam/AdGuardVPNExtension#165]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

2.1.7

### Environment

```markdown
- OS:Windows 11 Pro
- Browser: Яндекс
```

### Issue Details

При запуске расширения выдает, что призошла ошибка. Предложено связаться с вами.

**Comment by Shamros** [comment]
have same issue with chrome browser and win 11
![image](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/160658235/823c98cb-517a-42a8-b241-e48dd76a89de)

**Comment by alexx7311** [comment]
@BabiiIn @Shamros Здравствуйте! Расширение сейчас очень нестабильно работает в РФ, что связано с недавними блокировками. Попробуйте, пожалуйста, обновить версию до актуальной. Если не поможет, то мы рекомендуем установить полноценное [приложение для Windows](https://adguardvpn-help.com/).

Закрываем, как дубликат https://github.com/AdguardTeam/AdGuardVPNExtension/issues/148
