### ISSUE TITLE
Sign in with Google not working

### ISSUE THREAD

**Issue by cs-bekzod** [AdguardTeam/AdGuardVPNExtension#170]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

2.2.15

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS
- Browser: Google Chrome, Version 124.0.6367.60 (Official Build) (64-bit)
```

### Issue Details

Error alert: "Access blocked: This app’s request is invalid, You can’t sign in because this app sent an invalid request. You can try again later, or contact the developer about this issue. [Learn more about this error](https://developers.google.com/identity/protocols/oauth2/web-server#authorization-errors-redirect-uri-mismatch)
If you are a developer of this app, see [error details](https://accounts.google.com/).
Error 400: redirect_uri_mismatch"

### Screenshots

![IMG_20240420_231502](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/70283261/955b0d1c-5040-40e1-82aa-4b25dc182e04)

**Comment by D13410N3** [comment]
Hello. It should work now, can you please check?

**Comment by cs-bekzod** [comment]
hi, yes  its working, thank you
