### ISSUE TITLE
The extension doesn't work in Russia

### ISSUE THREAD

**Issue by kris-m1995** [AdguardTeam/AdGuardVPNExtension#172]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

2.2.15

### Environment

```markdown
- OS:windows 11
- Browser: Yandex
```

### Issue Details

Произошла ошибка
Пожалуйста, свяжитесь с нами, если вы продолжаете видеть это сообщение
![2024-04-25_21-58-23](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/168120019/e05aca69-d5c9-4591-86c7-739f5d04762a)

### Screenshots

![2024-04-25_21-58-23](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/168120019/5eb918ad-75e6-4699-a857-f0c6261d5553)

**Comment by alexx7311** [comment]
@kris-m1995 Здравствуйте! Подскажите, пожалуйста, вы сейчас в РФ находитесь?

**Comment by kris-m1995** [comment]
да 25.04.2024, 20:15, "alexx7311" ***@***.***>***@***.*** Здравствуйте! Подскажите, пожалуйста, вы сейчас в РФ находитесь?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by alexx7311** [comment]
@kris-m1995 Из-за блокировок VPN в России расширения сейчас будет работать очень нестабильно, поэтому рекомендуем установить десктопную версию.
Подробную информацию вы можете найти по ссылке https://github.com/AdguardTeam/AdGuardVPNExtension/issues/148#issuecomment-1761794877

Эту задачу закроем, как дубликат.
