### ISSUE TITLE
Show the number of online locations

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardVPNExtension#174]
### Issue Details

Currently, the extension shows the total number of locations, but doesn't show how many of the locations are online.

### Proposed solution

Instead of:

> All locations (50)

Write something like:

> Locations (50 total, 25 online)

**Comment by denis9229** [comment]
Ainar, I love you very much. But this option is only relevant for a few countries. We’re also trying to redirect extension users from these countries to the desktop app right away.

You’ve been waiting for a personal invitation :)
