### ISSUE TITLE
It won't connect

### ISSUE THREAD

**Issue by Taki-sobie** [AdguardTeam/AdGuardVPNExtension#178]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

2.2.20

### Browser version

Opera Gx  LVL5 (core: 109.0.5097.108) (arm64)   (Chromium:123.0.6312.124)

### OS version

macOS 12.7.5

### Issue Details

Steps to reproduce:
1. It just doesn't want to connect, the situation has been going on since yesterday
2.
3.

### Expected Behavior

To fix

### Actual Behavior

To fix

### Additional Information

 lack

**Comment by alexx7311** [comment]
@Taki-sobie Hello! 
Is the problem persisting with a particular server or is it not possible to connect to many servers? Your internet provider may not have a connection to our servers. This is usually a temporary problem, but if it keeps recurring, please do the following:
1. Reproduce the problem
2. Right click on the extension icon
3. Click Export logs

<details>
  <summary>Screenshot</summary>

  ![Screenshot](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/114913601/4cd5d980-f2c4-4dc0-afff-7db03ae18b37)

</details>

4. Attach the saved file to a comment in this issue.

**Comment by Taki-sobie** [comment]
Hello alexx7311,

The problem still occurs for all servers, today I am trying to connect constantly, I am attaching the list of logs
[20240604_174912_adg_vpn_v2.2.20.txt](https://github.com/user-attachments/files/15567183/20240604_174912_adg_vpn_v2.2.20.txt)

**Comment by alexx7311** [comment]
@Taki-sobie Could you please specify which country you are currently in?

**Comment by leo15dev** [comment]
@alexx7311 I had the same issue about a couple days  ago, and according to @Taki-sobie provided the log, I noticed there is a new domain in the log like  xxx.adguard-vpn.online, in my case is " v2.at-win.av2-3-1403-0.cname.pro.bkp-auth.adguard-vpn.online " (appeared in AdGuardHome log at 06/30 ), and the DNS answer is 1.2.3.4 ( by Google dns or cloudflare DNS). This could be the reason why caused this issue?

I had no issue with use the AdGuard VPN desktop app (Windows 11). 

Thank you!

**Comment by leo15dev** [comment]
@alexx7311 @Taki-sobie I finally figured out why I couldn’t connect. In my case, It was because *.poorcard.site was considered a threat in Zenarmor and was actively blocked. After adding it to the whitelist, the connection became as usual.
