### ISSUE TITLE
The extension doesn't work in Russia

### ISSUE THREAD

**Issue by oskarsan79** [AdguardTeam/AdGuardVPNExtension#179]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

2.2.20

### Browser version

Chrome Версия 125.0.6422.142; Yandex 24.4.2.967 corp (64-bit)

### OS version

windows 10 19042.2728

### Issue Details

Steps to reproduce:
1. Click on the extension to enable it
2.
3.

### Expected Behavior

enable VPN service

### Actual Behavior

Error

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by alexx7311** [comment]
Дубликат https://github.com/AdguardTeam/AdGuardVPNExtension/issues/148.
Пожалуйста, пользуйтесь десктопной версией AdGuard VPN.
