### ISSUE TITLE
Service doesnt work

### ISSUE THREAD

**Issue by gelnor** [AdguardTeam/AdGuardVPNExtension#181]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

2.2.20

### Browser version

 126.0.6478.127

### OS version

Windows 11

### Issue Details

Steps to reproduce:
1. After login page in chrome extension shows error. 

Произошла ошибка Пожалуйста, свяжитесь с нами, если вы продолжаете видеть это сообщение
Произошла ошибка Пожалуйста, свяжитесь с нами, если вы продолжаете видеть это сообщение
Произошла ошибка Пожалуйста, свяжитесь с нами, если вы продолжаете видеть это сообщение

### Actual Behavior

Steps to reproduce:
1. After login page in chrome extension shows error. 

Произошла ошибка Пожалуйста, свяжитесь с нами, если вы продолжаете видеть это сообщение
Произошла ошибка Пожалуйста, свяжитесь с нами, если вы продолжаете видеть это сообщение
Произошла ошибка Пожалуйста, свяжитесь с нами, если вы продолжаете видеть это сообщение

### Screenshots

<details><summary>Screenshot 1</summary>

![image](https://github.com/user-attachments/assets/6bfed12c-11a0-4e46-a4e7-182f684462fe)

</details>

**Comment by alexx7311** [comment]
Dup. of https://github.com/AdguardTeam/AdGuardVPNExtension/issues/148
Please use the [desktop version](https://adguardvpn-help.com/en/welcome.html) of AdGuard VPN.
