### ISSUE TITLE
Adguard Windows App Blocks Adguard VPN Connection (Chrome Extension)

### ISSUE THREAD

**Issue by MSerif** [AdguardTeam/AdGuardVPNExtension#183]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.2.20

### Environment

```markdown
- OS: Windows 10
- Other network-level software: AdGuard for Windows, Bitdefender Total Security
```

### Which DNS server do you use?

AdGuard DNS

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. For some time now, Adguard Chrome extension cannot establish a connection. 
2. If I turn off the protection of the Adguard Windows app, it connects.
3. If I turn protection on, it disconnects.
4.

### Expected Behavior

VPN has to connect to the server.

### Actual Behavior

VPN does not work.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

I also installed Adguard VPN's Windows app, and this problem occurs again. I have not changed any important settings in the Adguard Windows application. This problem has been going on for 1-2 months.

**Comment by alexx7311** [comment]
@MSerif We couldn't reproduce the problem. We turned on 'Permanent kill switch' option, then connected to Proton VPN, and then tried to connect to any location in AdGuard VPN extension. Everything seems fine.

Please reset the settings of Proton VPN and reinstall AdGuard VPN extension. 
Then describe step by step how to reproduce the problem.

**Comment by MSerif** [comment]
> @MSerif We couldn't reproduce the problem. We turned on 'Permanent kill switch' option, then connected to Proton VPN, and then tried to connect to any location in AdGuard VPN extension. Everything seems fine.
> 
> Please reset the settings of Proton VPN and reinstall AdGuard VPN extension. Then describe step by step how to reproduce the problem.

This problem hasn't recurred since I last wrote to you. I thought you had fixed the problem; it is not understandable. I have only changed "user agents" during this time.

Sorry for wasting your time.
