### ISSUE TITLE
Cannot Authenticate in Extension

### ISSUE THREAD

**Issue by Nemisor** [AdguardTeam/AdGuardVPNExtension#185]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

2.2.27

### Browser version

Chrome 131 and Brave 129

### OS version

ChromeOS Flex

### Issue Details

Steps to reproduce:
1. Install Extension from Chrome Web Store
2. Accept ToS and EULA
3. Attempt to authenticate using either email or google oath.

### Expected Behavior

Expected the usual process of email address/password and 2FA code, or the google account and 2FA code.

### Actual Behavior

Both attempts "fail to communicate with server". Confirmed connectivity on both the chromeos flex device, as well as a windows laptop, both using a cellular hotspot over USB after confirming that the cell itself can reach auth.adguard-vpn.com successfully. Neither the chromeos or windows extension can contact the auth server as of yesterday. Also tested both the stable and beta versions of the extension with the same result.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by ameshkov** [comment]
Could you please show a screenshot of this issue?

**Comment by GrAnd887** [comment]
> Could you please show a screenshot of this issue?

![image](https://github.com/user-attachments/assets/032293fe-96d6-41ea-aabd-d68f984baf5a)

**Comment by ameshkov** [comment]
@GrAnd887 if you're in Russia, the browser extension is not supposed to work there.

**Comment by windwak3r** [comment]
Dup. of https://github.com/AdguardTeam/AdGuardVPNExtension/issues/148
