### ISSUE TITLE
Why the hot reload is not working?

### ISSUE THREAD

**Issue by jiaxiangcheng** [AdguardTeam/AdGuardVPNExtension#188]
### Please answer the following questions for yourself before submitting a question.

- [ ] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Version: 2.2.30

Hi, I'm facing an issue where running `npm run dev` only builds the extension, but doesn't apply updates automatically. When I modify code related to the popup UI, the changes don't reflect in the UI until I manually re-run `npm run dev` and reload the extension in Chrome, which takes considerable time. Is there a way to enable hot reload? I noticed the `mode` and `devtool` fields are set correctly, as shown in the screenshot.

![image](https://github.com/user-attachments/assets/3ad4c2cb-da8a-4878-8f89-bea12ae6dc91)

**Comment by slavaleleka** [comment]
you may try to build an extension only for a specific browser + watch mode is available there, i.e.
`npm run dev chrome --watch`

**Comment by alexx7311** [comment]
@jiaxiangcheng Please leave a comment if you still have any questions.
