### ISSUE TITLE
VPN doesn't work now on my country.

### ISSUE THREAD

**Issue by gregorylutonj** [AdguardTeam/AdGuardVPNExtension#19]
Hello AdGuard team!
Previously, your VPN worked fine in my country, that is, in Turkmenistan. But, on February 10, the VPN began to be gradually turned off, because the meeting of the Halk Maslakhaty of the Milli Genesh of Turkmenistan was held, and extraordinary presidential elections will be held on March 12. Do you think your VPN will work after the elections?

**Comment by ameshkov** [comment]
Thank you for notifying us about this.

We've made some adjustments on our side and also added Turkmenistan to the list of countries we're monitoring closely.
Please check if the situation improved, restart the extension/program to see if our changes helped.

**Comment by Birbber** [comment]
I'm closing this issue. Feel free to re-open it or to add any additional information.

**Comment by Cliqin** [comment]
the VPN does not work in china now
