### ISSUE TITLE
adguard vpn is not working, there is no network after connecting.

### ISSUE THREAD

**Issue by x64bugreport** [AdguardTeam/AdGuardVPNExtension#194]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

2.2.32

### Browser version

chrome 131

### OS version

win10

### Issue Details

Steps to reproduce:
1.install from https://chromewebstore.google.com/detail/adguard-vpn-beta/kfjjacionkafnmnjhdghdfoinihnijgn
2.login in 
3.connect

### Actual Behavior

Please fix the problem of no network after connecting

### Screenshots

![1](https://github.com/user-attachments/assets/8729bd70-d9df-4130-b359-1bfe42d50c64)
![2](https://github.com/user-attachments/assets/be07b50f-56b2-4912-a05d-39d2e3eb13f4)

### Additional Information

this in my log
[20241203_160205_adg_vpn_v2.2.32.txt](https://github.com/user-attachments/files/17989461/20241203_160205_adg_vpn_v2.2.32.txt)
[20241203_154412_adg_vpn_v2.2.32.txt](https://github.com/user-attachments/files/17989463/20241203_154412_adg_vpn_v2.2.32.txt)

**Comment by alexx7311** [comment]
@x64bugreport, hello! Please use desktop version of AdGuard VPN https://github.com/AdguardTeam/AdGuardVPNForWindows/releases/tag/v2.4.1

The extension can easily be blocked in your country.
