### ISSUE TITLE
The New Jersey server makes Google/YT think I'm in... Azerbaijan?

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardVPNExtension#2]
Surely that's not supposed to be the case, right? 
![image](https://user-images.githubusercontent.com/22780683/103045518-1ded7400-4585-11eb-9efb-4dbf0b45f338.png)

Additionally, Seattle and sometimes New York seem to think I'm still in Norway (My homecountry). The other US servers have a spotless record so far, although I haven't tried those ones out all that much yet.

(For reproduction purposes on Google Search, make sure you're logged *out* of Google. I use the Chrome extension version of AdGuard DNS, with no additional DNS upstream chosen in the settings.)

**Comment by ameshkov** [comment]
It's not, but it could happen, IP addresses the hosting provider uses may be re-arranged.

When this happens, they usually report it to MaxMind, but it takes time for other parties to start using the updated database.

Here's what you can do to check this:
1. Find out what's your current IP is
2. Check it on MaxMind.com

If it points to the proper location, it means that the information is already updated there, and this is only a matter of time when it's updated in other IP databases.

**Comment by DandelionSprout** [comment]
`ipleak.net` gives me the IP addresses of `45.63.7.12` and `2001:19f0:5:67a4:5400:2ff:fee8:df30`, the former IPv4 address of which makes Google think I'm in Azerbaijan (The latter IPv6 address seems to acknowledge being in America while on `ipv6.google.com`).

MaxMind's "GeoIP2 Precision Web Service Demo" says `45.63.7.12` is indeed supposed to be in New Jersey, so I suppose that means Google should update its internal IP databases before long.
