### ISSUE TITLE
WebRTC allowlist?

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardVPNExtension#22]
Some web versions of chat apps, including Slack and Telegram Z, either cannot work without WebRTC or work much worse with it.  I wouldn't want to enable WebRTC for all domains, but I would like to have an allowlist for domains or well-known services where WebRTC is allowed.

**Comment by maximtop** [comment]
Browser Extension API [privacy.network](https://developer.chrome.com/docs/extensions/reference/privacy/#type-IPHandlingPolicy) section used in our extension doesn't allow to manage webrtc settings by domain.
