### ISSUE TITLE
Small popup for reset to default settings

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNExtension#23]
It would be good to enlarge this screen, the buttons are stuck to each other and cramped. In addition, the texts (menus) on the left are small in size. Texts such as the adblocker AdGuard can be made a little larger. To reproduce;
1. Add website for exclusions
2. Click website 
3. Click to reset default button

![bug1](https://user-images.githubusercontent.com/35523759/159590286-cf1dd81c-aa89-4832-910b-decdf30957ac.png)

![bug2](https://user-images.githubusercontent.com/35523759/159590289-d0abea19-8f62-4313-a39f-7d03f01d4bfd.png)

**Comment by homayouniarieed** [comment]
Vpn edgard

**Comment by homayouniarieed** [comment]
Vpn
