### ISSUE TITLE
The default DNS option use adguard non-filtering DNS

### ISSUE THREAD

**Issue by githubuser013** [AdguardTeam/AdGuardVPNExtension#25]
Why when I use the default DNS server under settings, The adguard non-filtering is selected?
Is this should happen, or the default DNS should be using my DNS server instead?
because there is another option for the non-filtering DNS.

AdGuard Extension VPN
Version 1.0.33

**Comment by Birbber** [comment]
@githubuser013 Hi! Adguard uses non-filtering dns by default. It works this way so that we have the opportunity to switch to another dns. We cannot use a user dns in the extension due to technical limitations.
