### ISSUE TITLE
Show bandwith amount

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNExtension#26]
It would be great if you add a feature that shows the amount of bandwidth for AG VPN apps. Thus, when we connect to any server we can see how much bandwidth is used.

**Comment by gork7777** [comment]
Good to know, thanks!

**Comment by Birbber** [comment]
@gork7777 Would you mind sharing your idea in more details? Is that about providing info on traffic used on a particular location? Or a general statistics?

**Comment by gork7777** [comment]
@Birbber A general statistic. The bandwidth used will be shown when we watch any video or do anything else.
