### ISSUE TITLE
Predefined Youtube group lacks actual video host.

### ISSUE THREAD

**Issue by deNoor** [AdguardTeam/AdGuardVPNExtension#29]
Youtube serves video and audio streams from `*.googlevideo.com/videoplayback?params` but Youtube preselect targets only the website.
![image](https://user-images.githubusercontent.com/25015943/165846047-c6504464-57f6-4aca-8ca1-829c90bafcac.png)

I believe that a user expects video to be VPNed too.

**Comment by maxikuzmin** [comment]
@deNoor  thanks for the question, we are going to fix this behavior. Closing this as duplicate #28
