### ISSUE TITLE
Deleted accounts remain active and logged-in 

### ISSUE THREAD

**Issue by Aikatsui** [AdguardTeam/AdGuardVPNExtension#3]
**How to reproduce**
1. Login to vpn extension and connect to any location.
2. Go to account login page on website then access to account
3. Delete account

Extension remain logged-in and connected. You can disconnect then connect to different locations etc and more.
Check if that reproducible on @VPNForAndroid @VPNForWindows @VPNForiOS @VPNForMac 

@denchik (Denis Vyazovoy)

**Comment by Chinaski1** [comment]
Hello!

I was able to reproduce your issue with the AdGuard VPN extension, we will check this situation on other platforms shortly.

Thank you for the information provided.

**Comment by TNTBOMBOM** [comment]
> we will check this situation on other platforms shortly.

it has been 2 years for this issue, still checking?

**Comment by alexx7311** [comment]
@TNTBOMBOM the issue has been fixed!
