### ISSUE TITLE
Massive amount of DNS queries generated by the extension

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardVPNExtension#30]
Browser: Firefox, 99 and 100.

Version: 1.0.40.

Problem: I can see massive amounts of queries for domains like `<hex string>.m9009-de-brl-01-<smaller hex string>.adguard.io` in the logs of my AdGuard Home.  Up to a hundred or so per second.  It seems like they are coming from the AdGuard VPN extension.

**Comment by maximtop** [comment]
Couldn't connect to the ip addresses returned by the browser.dns.resolve
