### ISSUE TITLE
Clicking again when the actions list was open it closes and opens

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNExtension#34]
When the Actions list is first opened in Exclusions, it opens normally but when you click it again, it closes and opens again. It should close when clicked again.

<details><summary>Video:</summary>

https://user-images.githubusercontent.com/35523759/172279581-90be545d-c39a-469c-a3b6-9cb6ae6f9704.mp4
</details>

**Comment by maximtop** [comment]
Thank you, we will fix it.
