### ISSUE TITLE
No separator in the context menu on Firefox

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNExtension#36]
### Steps to reproduce

1. Enter any website
2. Right click to open context menu

### Expected behavior

Just like when we open the context menu by right-clicking on an empty field of the page, there's should be a separator when right-clicking.
<details><summary>Screenshot:</summary>

![bug1](https://user-images.githubusercontent.com/35523759/172506250-2c90a3fb-a72e-429b-a006-2a640204096f.png)
</details>

### Actual behavior

There's no separator when you open the context menu for Firefox, but there's separator for Chrome.

<details><summary>Screenshot:</summary>

![Firefox](https://user-images.githubusercontent.com/35523759/172506255-25eb3201-f5c2-4dc4-911c-4f6f7d70c0de.png)
</details>

Browsers versions: Chrome v102.0.5005.63 - Firefox v101.0

**Comment by maxikuzmin** [comment]
@gork7777 thank you! We will consider your offer

**Comment by gork7777** [comment]
@maxikuzmin Nice to hear that!
