### ISSUE TITLE
Not working with some domains

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardVPNExtension#38]
Chrome 102.0.5005.63, AdGuard VPN 1.1.8
does not open nnmclub.to , nnmclub.to for a couple of days with any location. At the same time, Avira VPN opens these sites without problems.

**Comment by Birbber** [comment]
@YBS-PC Hi! Looks like our IPs were blocked by them. Unfortunately we can't change our IPs over 1 or several non-popular webpages. As I can see this webpage can be opened using Russian location, try using `Russia - Moscow` point.
