### ISSUE TITLE
Non-routable IPs detection is broken

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardVPNExtension#4]
## Steps to reproduce

1. Switch to the "Regular mode"
2. Try to open your router admin panel. For example, in my case this is `192.168.1.1` (or any other intranet page -- the actual IP depends on your network configuration)

## Expected result

The page is opened

## Actual result

Error 502

@AdguardTeam/qa-team @zebrum please add this to the regression test cases list

**Comment by maximtop** [comment]
Done
