### ISSUE TITLE
mygmrs.com returns blank page when WebRTC setting enabled in FireFox

### ISSUE THREAD

**Issue by Oniqqqq** [AdguardTeam/AdGuardVPNExtension#44]
Hey team! I've received a support request stating that website [mygmrs.com](url) returns a blank page when blocking WebRTC enabled, ignoring the whitelist. 
### Expected behaviour
![image](https://user-images.githubusercontent.com/38912221/176149285-c0558b09-3b0e-4581-9ded-41b8a88a0c77.png)
### Actual behavior
![image](https://user-images.githubusercontent.com/38912221/176149475-54549b44-e83d-4d4d-b62d-b74ae4f0878f.png)

**Comment by Birbber** [comment]
@Oniqqqq Hi! Thanks for the report. 
The issue is reproducible on our end, we'll take a look.

**Comment by tvinzz** [comment]
@Oniqqqq, open vpn settings and disable `Block WebRTC`

**Comment by Oniqqqq** [comment]
@tvinzz I see, thank you for the update. Yes, it would be nice if whitelisting a website worked for this setting too
