### ISSUE TITLE
[Feature request] Add mode switch to the main window

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardVPNExtension#5]
> Скажите, пожалуйста, насколько было бы сложно в открывающееся меню (которое открывается при нажатии на круглый значок на панели Chrome) добавить переключение между режимами работы, между обычным и выборочным? Не совсем удобно переключать в настройках расширения.

Helpdesk ID: 527806

**Comment by anastenko** [comment]
Здравствуйте.
Похожая функция уже предоставлена в контекстном меню: для этого необходимо перейти на нужную вам страницу -> кликнуть правой кнопкой мыши -> найти опцию "AdGuard VPN" -> выбрать один из режимов
