### ISSUE TITLE
Firefox Extension asks me to score on Chrome Store

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdGuardVPNExtension#56]
When the Extension randomly asks to score the Extension and you select some of stars, it asks your to open Chrome Store.
It should ask the user to score the Extension on Addons.mozilla.org (AMO) where the Extension is installed from.

It might be related to language which is German in my case.
Version 1.2.19

<details><summary>Screenshot-1:</summary>

![vpn1](https://user-images.githubusercontent.com/6276915/190453592-1025a06c-1cd4-4598-98e7-7b8f8ea775e5.png)

</details><br/>

<details><summary>Screenshot-2:</summary>

![vpn2](https://user-images.githubusercontent.com/6276915/190453617-3251dd4b-050d-47ec-bf0e-6003d43428dd.png)

</details><br/>

I don't like Google.

**Comment by tvinzz** [comment]
@Morku, thank you for your report.
It is known issue, already fixed and will be available with the next release (coming soon).
If the problem occurs in future, feel free to reopen the issue.
