### ISSUE TITLE
Add auto-connect setting when you disable AG VPN for Windows

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNExtension#57]
If you connect any location with AG VPN for Windows, the extension will be disabled automatically. If you try to connect from the extension while connected in the Windows application, it automatically gives a disconnected warning. If you exit from AG VPN for Windows and then restart the browser, extension will connect automatically. Most users do not realize that the extension is connected and it would be better to add a setting for it.

**Comment by denis9229** [comment]
We decided not to do this task yet
