### ISSUE TITLE
AdGuard VPN icon in Selective mode is active on empty tab

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardVPNExtension#6]
Использую AdGuard VPN в режиме "Выборочный". То есть ВПН всегда отключен и активен только на сайтах, которые я указал в списке. При этом значок ВПН становится активным (загорается), когда я открываю пустую новую вкладку в Google Chrome. Данное поведение значка отвлекает. Считаю такой режим работы неправильным, так как пустая вкладка не указана в списке сайтов.

Reported by 3265849.

**Comment by ameshkov** [comment]
Честно говоря у меня не повторяется такое поведение

**Comment by maximtop** [comment]
Done
