### ISSUE TITLE
DNS servers shifts to the right side after deleting custom DNS server

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNExtension#63]
### Issue Details
This issue is most likely caused by the scrollbar.

Stesp to reproduce:

1. Go to settings and DNS server
2. Add new custom DNS server
3. Then delete the your custom DNS server

- **Browser version:**
Chrome v106.0.5249.103
- **Operating system and version:**
Windows 10

### Expected Behavior

DNS server menu should be stay same position after deleting the custom DNS server.

### Actual Behavior

DNS server menu shifts to the right side after deleting the custom DNS server.

### Screenshots

<details><summary>Screenshot:</summary>

https://user-images.githubusercontent.com/35523759/195214633-7e8bac89-2ced-4dba-91f9-9da623d62ed2.mp4
</details>

**Comment by maximtop** [comment]
Thank you, we'll take a look.
