### ISSUE TITLE
Crashes the firefox on some websites

### ISSUE THREAD

**Issue by Bren828** [AdguardTeam/AdGuardVPNExtension#66]
Crashes the firefox on some websites 
Crashes on site: **meduza.io**

> **log**
> 
> AdapterDeviceID: 0x1b81
> AdapterDriverVersion: 31.0.15.2225
> AdapterSubsysID: 00000000
> AdapterVendorID: 0x10de
> Add-ons: %7B036a55b4-5e72-4d05-a06c-cba2dfcc134a%7D:9.6.1,%7B446900e4-71c2-419f-a6a7-df9c091e268b%7D:2022.10.0,adguard-vpn%40adguard.com:1.2.19,sponsorBlocker%40ajay.app:5.0.7,better-battlelog-live%40bfautism.ga:5.3.2,uBlock0%40raymondhill.net:1.44.4,%7B762f9885-5a13-4abd-9c77-433dcd38b8fd%7D:3.0.0.6,%7B221fdff2-37b9-44fd-a6de-93d38ca9cba1%7D:0.4.5,formautofill%40mozilla.org:1.0.1,pictureinpicture%40mozilla.org:1.0.0,screenshots%40mozilla.org:39.0.1,webcompat%40mozilla.org:105.2.0,addons-search-detection%40mozilla.com:2.0.0,google%40search.mozilla.org:1.2,wikipedia%40search.mozilla.org:1.1,ddg%40search.mozilla.org:1.1,firefox-compact-light%40mozilla.org:1.2
> AvailablePageFile: 16485900288
> AvailablePhysicalMemory: 17171140608
> AvailableVirtualMemory: 138522494672896
> BackgroundTaskMode: 0
> BlockedDllList: 
> BuildID: 20221007134813
> CPUMicrocodeVersion: 0xde
> ContentSandboxCapable: 1
> ContentSandboxLevel: 6
> ContentSandboxWin32kState: Win32k Lockdown enabled -- default value is true
> CrashTime: 1665747118
> DOMFissionEnabled: 1
> DOMIPCEnabled: 1
> ExperimentalFeatures: devtools.inspector.compatibility.enabled
> GPUProcessLaunchCount: 1
> GPUProcessStatus: Running
> HeadlessMode: 0
> InstallTime: 1665218725
> LastInteractionDuration: 20
> LauncherProcessState: 0
> ModuleSignatureInfo: {"Microsoft Corporation":["msvcp140.dll","VCRUNTIME140_1.dll","VCRUNTIME140.dll"],"Microsoft Windows":["nlansp_c.dll","winrnr.dll","pnrpnsp.dll","NapiNSP.dll","ondemandconnroutehelper.dll","TaskFlowDataEngine.dll","Windows.Security.Integrity.dll","edputil.dll","explorerframe.dll","dataexchange.dll","linkinfo.dll","cscapi.dll","ntshrui.dll","vaultcli.dll","Windows.Globalization.dll","windowsudk.shellcommon.dll","Windows.FileExplorer.Common.dll","ktmw32.dll","directmanipulation.dll","Windows.UI.Immersive.dll","twinapi.dll","dbgcore.dll","wininet.dll","wscapi.dll","deviceaccess.dll","SensorsNativeApi.V2.dll","SensorsUtilsV2.dll","SensorsApi.dll","OneCoreCommonProxyStub.dll","Windows.StateRepositoryPS.dll","srvcli.dll","iertutil.dll","urlmon.dll","Windows.UI.dll","dbghelp.dll","wsock32.dll","Bcp47Langs.dll","textinputframework.dll","AudioSes.dll","msimg32.dll","d3d9.dll","winmm.dll","npmproxy.dll","windows.staterepositoryclient.dll","windows.staterepositorycore.dll","Windows.System.Launcher.dll","mscms.dll","MMDevAPI.dll","OneCoreUAPCommonProxyStub.dll","FWPUCLNT.DLL","rasadhlp.dll","PortableDeviceTypes.dll","drvstore.dll","dhcpcsvc6.DLL","cryptnet.dll","dhcpcsvc.dll","version.dll","twinapi.appcore.dll","winhttp.dll","CoreUIComponents.dll","wshbth.dll","avrt.dll","directxdatabasehelper.dll","xmllite.dll","netprofm.dll","propsys.dll","taskschd.dll","webauthn.dll","msvcp110_win.dll","d3dcompiler_47.dll","DWrite.dll","dcomp.dll","CoreMessaging.dll","wtsapi32.dll","winnsi.dll","uxtheme.dll","DXCore.dll","dxgi.dll","dwmapi.dll","resourcepolicyclient.dll","WinTypes.dll","windows.storage.dll","slc.dll","netutils.dll","IPHLPAPI.DLL","dnsapi.dll","rsaenh.dll","winsta.dll","kernel.appcore.dll","ntmarta.dll","umpdc.dll","powrprof.dll","sspicli.dll","mswsock.dll","gpapi.dll","userenv.dll","cryptsp.dll","cryptbase.dll","wldp.dll","ntasn1.dll","ncrypt.dll","bcrypt.dll","msasn1.dll","cfgmgr32.dll","devobj.dll","profapi.dll","crypt32.dll","bcryptPrimitives.dll","gdi32full.dll","KERNELBASE.dll","win32u.dll","ucrtbase.dll","msvcp_win.dll","wintrust.dll","clbcatq.dll","oleaut32.dll","gdi32.dll","combase.dll","advapi32.dll","ole32.dll","shlwapi.dll","shell32.dll","imagehlp.dll","msctf.dll","ws2_32.dll","kernel32.dll","imm32.dll","SHCore.dll","psapi.dll","sechost.dll","msvcrt.dll","setupapi.dll","nsi.dll","user32.dll","rpcrt4.dll","ntdll.dll"],"Mozilla Corporation":["firefox.exe","xul.dll","libGLESv2.dll","nss3.dll","osclientcerts.dll","freebl3.dll","nssckbi.dll","softokn3.dll","libEGL.dll","mozglue.dll","lgpllibs.dll"]}
> Notes: FP(D00-L1000-W00001000-T000) 
> DWrite? DWrite+ WR? WR+ WebGL? EGL? EGL- GL Context? GL Context+ WebGL+ 
> ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
> ProductName: Firefox
> RDDProcessStatus: Running
> ReleaseChannel: release
> SafeMode: 0
> SecondsSinceLastCrash: 854
> StartupCrash: 0
> StartupTime: 1665746341
> SubmittedFrom: Client
> SystemMemoryUsePercentage: 19
> TelemetryEnvironment: {"build":{"applicationId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","applicationName":"Firefox","architecture":"x86-64","buildId":"20221007134813","version":"105.0.3","vendor":"Mozilla","displayVersion":"105.0.3","platformVersion":"105.0.3","xpcomAbi":"x86_64-msvc","updaterAvailable":true},"partner":{"distributionId":null,"distributionVersion":null,"partnerId":null,"distributor":null,"distributorChannel":null,"partnerNames":[]},"system":{"memoryMB":20447,"virtualMaxMB":134217728,"cpu":{"isWindowsSMode":false,"count":4,"cores":2,"vendor":"GenuineIntel","family":6,"model":158,"stepping":9,"l2cacheKB":256,"l3cacheKB":3072,"speedMHz":3600,"extensions":["hasMMX","hasSSE","hasSSE2","hasSSE3","hasSSSE3","hasSSE4_1","hasSSE4_2","hasAES"]},"os":{"installYear":2022,"hasSuperfetch":false,"hasPrefetch":false,"name":"Windows_NT","version":"10.0","locale":"en-US","servicePackMajor":0,"servicePackMinor":0,"windowsBuildNumber":22621,"windowsUBR":674},"hdd":{"binary":{"model":"KINGSTON SA400S37120G","revision":"03070009","type":"SSD"},"profile":{"model":"KINGSTON SA400S37120G","revision":"03070009","type":"SSD"},"system":{"model":"KINGSTON SA400S37120G","revision":"03070009","type":"SSD"}},"gfx":{"D2DEnabled":true,"DWriteEnabled":true,"ContentBackend":"Skia","Headless":false,"EmbeddedInFirefoxReality":false,"adapters":[{"description":"NVIDIA GeForce GTX 1070","vendorID":"0x10de","deviceID":"0x1b81","subsysID":"00000000","RAM":8192,"driver":"C:\\Windows\\System32\\DriverStore\\FileRepository\\nv_dispi.inf_amd64_1b5e80ff87b1f5c8\\nvldumdx.dll,C:\\Windows\\System32\\DriverStore\\FileRepository\\nv_dispi.inf_amd64_1b5e80ff87b1f5c8\\nvldumdx.dll,C:\\Windows\\System32\\DriverStore\\FileRepository\\nv_dispi.inf_amd64_1b5e80ff87b1f5c8\\nvldumdx.dll,C:\\Windows\\System32\\DriverStore\\FileRepository\\nv_dispi.inf_amd64_1b5e80ff87b1f5c8\\nvldumdx.dll C:\\Windows\\System32\\DriverStore\\FileRepository\\nv_dispi.inf_amd64_1b5e80ff87b1f5c8\\nvldumd.dll,C:\\Windows\\System32\\DriverStore\\FileRepository\\nv_dispi.inf_amd64_1b5e80ff87b1f5c8\\nvldumd.dll,C:\\Windows\\System32\\DriverStore\\FileRepository\\nv_dispi.inf_amd64_1b5e80ff87b1f5c8\\nvldumd.dll,C:\\Windows\\System32\\DriverStore\\FileRepository\\nv_dispi.inf_amd64_1b5e80ff87b1f5c8\\nvldumd.dll","driverVendor":null,"driverVersion":"31.0.15.2225","driverDate":"10-6-2022","GPUActive":true}],"monitors":[{"screenWidth":1600,"screenHeight":900,"refreshRate":60,"pseudoDisplay":false}],"features":{"compositor":"webrender","hwCompositing":{"status":"available"},"gpuProcess":{"status":"available"},"wrQualified":{"status":"available"},"webrender":{"status":"available"},"wrCompositor":{"status":"available"},"wrSoftware":{"status":"available"},"openglCompositing":{"status":"unused"},"omtp":{"status":"unused"},"d3d11":{"status":"available","version":45312,"warp":false,"textureSharing":true,"blocklisted":false},"d2d":{"status":"available","version":"1.1"}}},"appleModelId":null,"hasWinPackageId":false,"sec":{"antivirus":["Антивирусная программа Microsoft Defender"],"antispyware":null,"firewall":["Брандмауэр Windows"]},"isWow64":false,"isWowARM64":false},"settings":{"blocklistEnabled":true,"e10sEnabled":true,"e10sMultiProcesses":8,"fissionEnabled":true,"telemetryEnabled":false,"locale":"ru","intl":{"requestedLocales":["ru"],"availableLocales":["ru","en-US"],"appLocales":["ru","en-US"],"systemLocales":["en-US","ru-RU"],"regionalPrefsLocales":["ru-RU"],"acceptLanguages":["ru-RU","ru","en-US","en"]},"update":{"channel":"release","enabled":true,"autoDownload":true,"background":true},"userPrefs":{"app.shield.optoutstudies.enabled":false,"app.update.service.enabled":false,"browser.fixup.alternate.enabled":false,"browser.search.region":"RU","browser.search.widget.inNavBar":false,"browser.startup.page":3,"browser.urlbar.autoFill":true,"browser.urlbar.autoFill.adaptiveHistory.enabled":false,"browser.urlbar.dnsResolveSingleWordsAfterSearch":0,"browser.urlbar.quicksuggest.dataCollection.enabled":false,"browser.urlbar.suggest.quicksuggest.nonsponsored":false,"browser.urlbar.suggest.quicksuggest.sponsored":false,"browser.urlbar.suggest.bestmatch":true,"media.gmp-gmpopenh264.lastInstallStart":1663710213,"media.gmp-gmpopenh264.lastDownload":1663710213,"media.gmp-gmpopenh264.lastUpdate":1663710213,"media.gmp-manager.lastCheck":1665746398,"media.gmp-manager.lastEmptyCheck":1665746398,"network.trr.strict_native_fallback":false,"privacy.trackingprotection.enabled":true,"privacy.donottrackheader.enabled":true,"signon.generation.enabled":false,"signon.rememberSignons":false,"widget.content.allow-gtk-dark-theme":false,"widget.content.gtk-high-contrast.enabled":true},"sandbox":{"effectiveContentProcessLevel":6,"contentWin32kLockdownState":15},"launcherProcessState":0,"addonCompatibilityCheckEnabled":true,"isDefaultBrowser":true,"attribution":{"campaign":"%2528not%2Bset%2529","content":"%2528not%2Bset%2529","dltoken":"474f8902-107b-4bf4-8219-6fe230c1a8fe","experiment":"%2528not%2Bset%2529","medium":"referral","source":"yandex.ru","ua":"edge","variation":"%2528not%2Bset%2529"},"defaultSearchEngine":"google-com-nocodes","defaultSearchEngineData":{"loadPath":"[other]addEngineWithDetails:google@search.mozilla.org","name":"Google","origin":"default","submissionURL":"https://www.google.com/search?q="}},"profile":{"creationDate":19255,"firstUseDate":19255},"addons":{"activeAddons":{"adguard-vpn@adguard.com":{"version":"1.2.19","scope":1,"type":"extension","updateDay":19255,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Анонимайзер AdGuard VPN для быстрого и безопасного сёрфинга в интернете. Скройте IP и сохраняйте ано","name":"AdGuard VPN — быстрый и безопасный proxy","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19255,"signedState":2},"better-battlelog-live@bfautism.ga":{"version":"5.3.2","scope":1,"type":"extension","updateDay":19255,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Battlelog Fix Browser Addon! Add many improvements and new features - for example stunning weapon in","name":"Better Battlelog Fix(BBLog)","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19255,"signedState":2},"uBlock0@raymondhill.net":{"version":"1.44.4","scope":1,"type":"extension","updateDay":19255,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Наконец-то, быстрый и эффективный блокировщик для браузеров.","name":"uBlock Origin","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19255,"signedState":2},"{762f9885-5a13-4abd-9c77-433dcd38b8fd}":{"version":"3.0.0.6","scope":1,"type":"extension","updateDay":19257,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Возвращает способность видеть дизлайки","name":"Return YouTube Dislike","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19255,"signedState":2},"{036a55b4-5e72-4d05-a06c-cba2dfcc134a}":{"version":"9.6.1","scope":1,"type":"extension","updateDay":19269,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Перевод страниц в режиме реального времени с помощью Google или Яндекс.","name":"TWP - Translate Web Pages","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19255,"signedState":2},"sponsorBlocker@ajay.app":{"version":"5.0.7","scope":1,"type":"extension","updateDay":19270,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Пропускайте спонсорские вставки, просьбы подписаться и другое в видео на YouTube. Отправляйте информ","name":"SponsorBlock для YouTube - Пропускайте спонсорские вставки","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19255,"signedState":2},"formautofill@mozilla.org":{"version":"1.0.1","scope":1,"type":"extension","updateDay":19250,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":null,"name":"Form Autofill","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19250},"pictureinpicture@mozilla.org":{"version":"1.0.0","scope":1,"type":"extension","updateDay":19250,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Fixes for web compatibility with Picture-in-Picture","name":"Picture-In-Picture","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19250},"screenshots@mozilla.org":{"version":"39.0.1","scope":1,"type":"extension","updateDay":19250,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Take clips and screenshots from the Web and save them temporarily or permanently.","name":"Firefox Screenshots","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19250},"webcompat@mozilla.org":{"version":"105.2.0","scope":1,"type":"extension","updateDay":19250,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Urgent post-release fixes for web compatibility.","name":"Web Compatibility Interventions","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19250},"{221fdff2-37b9-44fd-a6de-93d38ca9cba1}":{"version":"0.4.5","scope":1,"type":"extension","updateDay":19277,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Show Twitch chat on top of the stream player. Read chat, send messages, claim points, and more, with","name":"Anu Twitch Chat Overlay","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19277,"signedState":2},"{446900e4-71c2-419f-a6a7-df9c091e268b}":{"version":"2022.10.0","scope":1,"type":"extension","updateDay":19278,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Защищенный и бесплатный менеджер паролей для всех ваших устройств.","name":"Bitwarden - бесплатный менеджер паролей","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19255,"signedState":2}},"theme":{"id":"firefox-compact-light@mozilla.org","blocklisted":false,"description":"Тема со светлой цветовой гаммой.","name":"Светлая","userDisabled":false,"appDisabled":false,"version":"1.2","scope":4,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19255,"updateDay":19255},"activeGMPlugins":{"gmp-gmpopenh264":{"version":"1.8.1.2","userDisabled":false,"applyBackgroundUpdates":1},"gmp-widevinecdm":{"version":"4.10.2449.0","userDisabled":false,"applyBackgroundUpdates":1}}},"services":{"accountEnabled":true,"syncEnabled":true}}
> Throttleable: 1
> TotalPageFile: 22782054400
> TotalPhysicalMemory: 21439877120
> TotalVirtualMemory: 140737488224256
> UptimeTS: 7775.16415
> UtilityProcessStatus: Running
> Vendor: Mozilla
> Version: 105.0.3
> Winsock_LSP: Hyper-V RAW : 2 : 34 : 1 : 1 : 0x20026 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 1234191b-4bf7-4ca7-86e0-dfd7c32b5445 
>  MSAFD Tcpip [TCP/IPv6] : 2 : 23 : 1 : 6 : 0x20066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : f9eab0c0-26d4-11d0-bbbf-00aa006c34e4 
>  MSAFD Tcpip [UDP/IPv6] : 2 : 23 : 2 : 17 : 0x20609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : f9eab0c0-26d4-11d0-bbbf-00aa006c34e4 
>  MSAFD Tcpip [RAW/IPv6] : 2 : 23 : 3 : 0 : 0x20609 : 0xc : %SystemRoot%\system32\mswsock.dll :  : f9eab0c0-26d4-11d0-bbbf-00aa006c34e4 
>  MSAFD Tcpip [TCP/IP] : 2 : 2 : 1 : 6 : 0x20066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : e70f1aa0-ab8b-11cf-8ca3-00805f48a192 
>  MSAFD Tcpip [UDP/IP] : 2 : 2 : 2 : 17 : 0x20609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : e70f1aa0-ab8b-11cf-8ca3-00805f48a192 
>  MSAFD Tcpip [RAW/IP] : 2 : 2 : 3 : 0 : 0x20609 : 0xc : %SystemRoot%\system32\mswsock.dll :  : e70f1aa0-ab8b-11cf-8ca3-00805f48a192 
>  Поставщик услуг RSVP TCPv6 : 2 : 23 : 1 : 6 : 0x22066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
>  Поставщик услуг RSVP TCP : 2 : 2 : 1 : 6 : 0x22066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
>  Поставщик услуг RSVP UDPv6 : 2 : 23 : 2 : 17 : 0x22609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
>  Поставщик услуг RSVP UDP : 2 : 2 : 2 : 17 : 0x22609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
>  AF_UNIX : 2 : 1 : 1 : 0 : 0x20026 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : a00943d9-9c2e-4633-9b59-0057a3160994 
>  MSAFD L2CAP [Bluetooth] : 2 : 32 : 1 : 256 : 0x20006 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9fc48064-7298-43e4-b7bd-181f2089792a 
>  MSAFD RfComm [Bluetooth] : 2 : 32 : 1 : 3 : 0x20026 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9fc48064-7298-43e4-b7bd-181f2089792a
> useragent_locale: ru

**Comment by leo15dev** [comment]
Same here, v1.3.19 not fixed it.

**Comment by Birbber** [comment]
@leo15dev Hi! Could you turn other extensions off and try to reproduce the issue?

**Comment by leo15dev** [comment]
> @leo15dev Hi! Could you turn other extensions off and try to reproduce the issue?

@Birbber Hello! It seems to no crash when I just turn other extension off, but still can not connect to some web site. The same web site I could connect by AdGuard VPN extension in chrome.  I had already sent the report by the  AdGuard VPN extension's Report a bug before. Thank you!

**Comment by Birbber** [comment]
Could you show us a screenshot of devtools' `console` tab when you try to connect to one of such webpages?
Also please share the number of the report you've sent before.

**Comment by leo15dev** [comment]
![20221108](https://user-images.githubusercontent.com/68909774/200599968-87fb52c4-f67a-4514-bd04-7399b1118e63.png)
@Birbber here is the screenshot, and the website can be connect in chrome by the AdGuard VPN extension. And sorry I can not find the  number of the report I have sent before (where can I find it?).

**Comment by Birbber** [comment]
> where can I find it?

Usually it's shown in the initial email message from AdGuard Support (looks like [this](uploads.adguard.org/support_ticket.png)).

It looks like some local issue on your end. We couldn't reproduce it, so it's probably not related to our extension.
