### ISSUE TITLE
Prevents Ublock Origin Filter List updates

### ISSUE THREAD

**Issue by S7venLights** [AdguardTeam/AdGuardVPNExtension#67]
The VPN extension on Firefox for linux seems to be preventing all or some of the filter lists of the Extension; Ublock Origin from updating.
When disconnected updates work as soon as connected the updates fail with a broken link icon.

**Comment by S7venLights** [comment]
Seems it may have been because I have NextDNS configured system wide with 'DNS Rebinding Protection' on. 
It seems it was interfering with Adguard Extensions connection.

**Comment by maximtop** [comment]
Did you succeed to download updates?

**Comment by S7venLights** [comment]
Even with NextDNS rebinding protection off, I had a similar issue tоԁау after a PC reboot, where the browser couldn't connect to the VPN or resolve any website. Other applications worked fine, so it seems Adguard VPN extension and NextDNS CLI aren't playing well together. Restarting NextDNS from CLI seemed to recitify the issue.

As for updating ublock blockists, even when other websites were working with adguard, the lists aren't able to update without disconnecting the VPN. And from Ublocks settings interface, there's no way to 'disable VPN on this website' in adguard.

**Comment by maximtop** [comment]
> And from Ublocks settings interface, there's no way to 'disable VPN on this website' in adguard.
You can try to add ublock server URLs to exclusions manually.

**Comment by Birbber** [comment]
@S7venLights Have you tried adding ublock server URLs to exclusions manually? Did it help?

**Comment by S7venLights** [comment]
Hi, no I use multiple block lists and they update from different places. So this would be impractical. 
Is there not a way for the extinctions to connect through the adguard Proxy?

**Comment by S7venLights** [comment]
Could you build in a setting to Disable Adguard for the browser extensions. In the same fashion as "Disable VPN for this Website"?

**Comment by mozartinio** [comment]
@S7venLights 
Unfortunately we cannot do that but we are always open to new suggestions. 
So thank you!
