### ISSUE TITLE
Cannot access domain

### ISSUE THREAD

**Issue by tismega** [AdguardTeam/AdGuardVPNExtension#68]
cannot access [pan.baidu.com](https://pan.baidu.com)

**Comment by Birbber** [comment]
Couldn't reproduce on our end. Does it depend on the location you choose?

**Comment by tismega** [comment]
No, the result is the same no matter what location I choose.

**Comment by tismega** [comment]
No, the result is the same no matter what location I choose.

**Comment by Birbber** [comment]
The webpage is accessible from our end. Could you show us a screenshot of `console` tab from `background.html` ?

**Comment by Birbber** [comment]
@tismega This domain is blocked in most of the countries, so it's not the issue of our extension. Try connecting to RU location to reach it.
