### ISSUE TITLE
Make notification popups Dark theme when 500 MB left and Monthly data limit reached

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNExtension#69]
When using Dark theme, make Dark theme popup for the following notification popups:
I didn't take picture for the `You’re running out of free data: 500MB left` popup but this is same with the `Monthly data limit reached` popup.
You can make Dark theme for that two popups.

<details><summary>Monthly data limit reached</summary>

![vpn](https://user-images.githubusercontent.com/35523759/201556059-488b793b-ed96-46b3-976b-54b460d1f404.png)
</details>

**Comment by maximtop** [comment]
Do you use a Light theme for the browser and a Dark theme for the extension?

**Comment by gork7777** [comment]
@maximtop I using Dark theme for browser and System default for the extension. My browser was Firefox.

**Comment by maximtop** [comment]
> @maximtop I using Dark theme for browser and System default for the extension. My browser was Firefox.

@gork7777 if I correctly understood you, we can't manage the theme for notification popups they are managed by the browser itself

**Comment by gork7777** [comment]
No problem then, I just did small suggest for that :)
