### ISSUE TITLE
Ninjastream.to - It break video

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardVPNExtension#7]
Steps to reproduce:

https://ninjastream.to/watch/apwQEp2g2APKe

- Open AdGuard VPN and add Ninjastream site to whitelist.
- Click the play button
- It shows this error: `HLS.js error: networkError - fatal: true - manifestLoadError`

![nnj](https://user-images.githubusercontent.com/74098460/115943656-de468280-a4b9-11eb-88f6-bcde91267a0c.png)

The problem only occurs if the site has been whitelisted. When you enable the VPN again on the same link, the video works fine.

---

VPN settings:

- Version: 0.9.18
- Browser - Chrome 90
- Win 10
- Free account
- Regular Mode
- WebRTC setting is off.
- DNS server setting selected by default.

**Comment by ameshkov** [comment]
It looks as if it was blocked for VPN., we'll see if we can add it to the streaming services list

**Comment by zzebrum** [comment]
It seems to be working ok now.
