### ISSUE TITLE
Unauthorized request to proxy server

### ISSUE THREAD

**Issue by zhelvis** [AdguardTeam/AdGuardVPNExtension#73]
Sometimes extension cannot auth on proxy server. Seems like we missed some data on requesting.
![image](https://user-images.githubusercontent.com/25105808/209150654-2586d6c3-d09c-4d32-80b5-200438efc7bc.png)

**Comment by tvinzz** [comment]
AdGuard VPN Browser Extension version
1.3.42

Environment
- OS: macOS Monterey
- Browser: Edge 108.0.1462.76 (x86_64)

<img width="820" alt="image" src="https://user-images.githubusercontent.com/15062885/217085927-a1ed7478-ed76-4523-897f-8d13b8127042.png">

**Comment by BOR-LAND** [comment]
Opera One(версия: 100.0.4815.54)
AdGuardVPNExtension 2.0.16 [VPN включён везде] + включено использование в режиме инкогнито
1. Создать приватное окно > использовать адресную строку для поиска
2. Создать приватное окно > открыть новую вкладку > использовать поле поиска экспресс-панели
3. Создать приватное окно > открыть новую вкладку > открыть любую закладку экспресс-панели
4. Просто перезапустить браузер:
![ужас](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/93826441/21fd7e39-e8a8-499a-aba8-9d577d9081a1)

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardVPNExtension/issues/110
