### ISSUE TITLE
I can't access the official Huorong forum when using the Frankfurt node in Germany.

### ISSUE THREAD

**Issue by KevinGu0611** [AdguardTeam/AdGuardVPNExtension#74]
1.Disconnect from the VPN.
2.Can be successfully accessed bbs.huorong.cn
3.Connect to the Frankfurt node VPN in Germany.
4.bbs.huorong.cn cannot be accessed.
Page error: There may be a problem with the page with the https://bbs.huorong.cn/ URL, or it has been permanently moved to a new URL.
ERR_TUNNEL_CONNECTION_FAILED

**Comment by mozartinio** [comment]
@KevinGu0611 Hello!
You can add this website to exclusions list
Can you try it?
If the issue will still persist let us know and we will figure out the reason

**Comment by KevinGu0611** [comment]
> @KevinGu0611你好！您可以将此网站添加到排除列表中 你能试试吗？如果问题仍然存在，请告诉我们，我们将找出原因

@mozartinio Hello! Adding that website to the exclusion is accessible, that is, opening a VPN does not exclude that website is inaccessible.

**Comment by mozartinio** [comment]
@KevinGu0611 
Hello!
We are looking for the cause of the problem then will fix it
Stay tuned!

**Comment by KevinGu0611** [comment]
> @KevinGu0611 你好！我们正在寻找问题的原因，然后会解决它 敬请期待！

@mozartinio Hello! I also can't open the Edelweisss Forum when using the node in Paris, France.Now the Frankfurt node in Germany is accessible.

**Comment by mozartinio** [comment]
@KevinGu0611 
We figured out the problem and it's not related to our extension
The problem is on the side of the sites
