### ISSUE TITLE
chrome app stopped working in china, 

### ISSUE THREAD

**Issue by Xmaozi** [AdguardTeam/AdGuardVPNExtension#75]
I am an user in China, the chrome app stopped working and I can't work without VPN, please help.

I bought 2 years service, if the app can;t fix the issue, can i get my money back?

**Comment by mozartinio** [comment]
@Xmaozi 
Hello!
We are aware of this and already working on it
Stay tuned!

**Comment by KevinGu0611** [comment]
> @Xmaozi 你好！我们意识到这一点，并且已经在努力 敬请期待！

@Xmaozi Hello! Now that AdGuardVPN is no longer available in China, please fix it as soon as possible.Also, the official website of AdGuardVPN has also been banned in China.Thank you!

**Comment by ameshkov** [comment]
Just in case, there's a mirror website https://adguard-vpn.net/

Regarding the Chrome Store, you could probably try MS Edge and Edge Add-ons store.
