### ISSUE TITLE
[Question] Why did Turkey server switch from free to paid?

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNExtension#77]
### Issue Details

Turkey location has been available for free for a few years, but switched to paid 1-2 months ago. Is there a reason for this?

**Comment by ameshkov** [comment]
It is much harder to maintain a big number of free locations. When there's a surge in new users registrations (like it was with millions of Iranian users), it becomes extremely hard to maintain good quality on all free locations. So after all we decided to keep a small number of free locations where we can scale the number of servers quickly when it's required.
