### ISSUE TITLE
DoodStream — Network error!

### ISSUE THREAD

**Issue by yoask889** [AdguardTeam/AdGuardVPNExtension#8]
https://doodstream.com/d/541lisgdvrzw

Embed link:
https://dood.so/e/mmi1vaj7swam62jv974vvlluzfd72y8

---

Steps to reproduce:

- Add the DoodStream link to the exception and refresh the page.

- Try to play the video

- It show a `Network error` warning.

<details>
 <summary>Screenshot</summary>
 
![bpconcjcammlapcogcnnelfmaeghhagj](https://user-images.githubusercontent.com/83504684/116785006-f319ac00-aa9f-11eb-8703-1abebbbca4c0.png)

</details>

- Enable again VPN on the DoodStream site. (remove the site from the exception)
- Try to play the video.
- Video works fine.

<details>
 <summary>Screenshot</summary>
 
![d2_censored](https://user-images.githubusercontent.com/83504684/116785318-a3d47b00-aaa1-11eb-8d02-e2a3c378a839.jpg)

</details>

<details>
 <summary>Screenshot</summary>
 
![d1111](https://user-images.githubusercontent.com/83504684/116785723-bb146800-aaa3-11eb-9f9b-ec4a98dd79e8.png)

</details>

---

VPN settings:

    Version: 0.11.3
    Browser - Chrome 90
    Win 10
    Free account
    Regular Mode
    WebRTC setting is off.
    DNS server : Default

**Comment by zzebrum** [comment]
@yoask889 you need to add `yq81ud.dood.video` to exclusions too.
