### ISSUE TITLE
AdGuardVPN is no longer available in China.

### ISSUE THREAD

**Issue by KevinGu0611** [AdguardTeam/AdGuardVPNExtension#81]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

1.3.42

### Environment

```markdown
- OS:Windows 11
- Browser:Microsoft edge
```

### Issue Details

AdGuardVPN is no longer available in China.No usable nodes have been loaded.

### Expected Behavior

I hope that the developers can fix it as soon as possible and restore the VPN to Chinese users.

### Screenshots

<img width="237" alt="image" src="https://user-images.githubusercontent.com/107782505/217476765-a522fc76-9013-433b-b146-628ebf2e6603.png">

### Additional Information

Hope to fix it soon, thank you!

**Comment by mozartinio** [comment]
@KevinGu0611 
Hello!
Thank you for reporting the problem. We'll try to do our best but there's not much we can do about it (cause of Chinese firewall).
I'll close the issue but as soon as we have a chance to fix it we'll do it
