### ISSUE TITLE
Impossible enable, if adguard services are not available without vpn

### ISSUE THREAD

**Issue by 0x131315** [AdguardTeam/AdGuardVPNExtension#83]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

1.3.42

### Environment

```markdown
- OS:Ubuntu 22.04
- Browser:Chrome 111.0.5563.64
```

### Issue Details

If adguard services are not available without vpn, adguard vpn extension cannot be enabled. You can log in to it through another vpn extension, but when you try to enable adguard vpn, it turns off all third-party vpn extensions and loses the ability to turn itself on.
For Windows, it is possible to enable adguard vpn in the browser if you enable adguard vpn in Windows, then enable it in the browser, and then disable it in Windows.
For Linux, this is not possible.
Probably need third-party bootstrap services, for enable extension.

### Expected Behavior

Ability to enable VPN if adguard services are unavailable

**Comment by mozartinio** [comment]
@0x131315 
Hello!
How often it happens? On particular sites or everywhere?
Can you please send your VPN and AdGuard console while this issue?

**Comment by mozartinio** [comment]
@0x131315 any news?

**Comment by mozartinio** [comment]
@0x131315 
Good that is no reproduce anymore 
Im closing the issue if it will reproduce again pls feel free to reopen this issue
