### ISSUE TITLE
Contrast enhancement for `VPN is disabled on this website` text

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNExtension#84]
### Issue Details

Using v1.4.14 Beta. Contrast can be improved for this text because it is not very visible.

<details><summary>Light theme 1:</summary>

![image](https://user-images.githubusercontent.com/35523759/226498110-0dd1382e-66b7-4d3c-9fb8-ca27fdbcf073.png)
</details>

<details><summary>Light theme 2:</summary>

![image](https://user-images.githubusercontent.com/35523759/226498173-0909f036-1521-4cef-ab35-ee2cab08a9ce.png)
</details>

<details><summary>Dark theme 1:</summary>

![image](https://user-images.githubusercontent.com/35523759/226498273-1c780b52-4418-4e11-a483-fe19cb9ce13f.png)
</details>

<details><summary>Dark theme 2:</summary>

![image](https://user-images.githubusercontent.com/35523759/226498392-cda06659-2772-4dab-9823-e5a2a6b74dfa.png)
</details>

### Proposed solution

The text could be more visible. You can set the contrast as in `Disable VPN for this website` text.

**Comment by mozartinio** [comment]
@gork7777 Hello!
We will think about your request
Thank you!
