### ISSUE TITLE
Allow to search by country code (ISO format, e.g. `US`)

### ISSUE THREAD

**Issue by contribucious** [AdguardTeam/AdGuardVPNExtension#85]
# Issue Details

###### _(:wave: Hi there! Thank you very much in advance.)_
&nbsp;
In the current situation, although the icon of the extension (v1.3.42) displays the country code, this cannot be used for a search:
<details>
<summary><strong>View screenshot …</strong></summary>
&nbsp;

![firefox_4csRgJGZjf](https://user-images.githubusercontent.com/4764956/226533376-942fec01-a0e8-4af9-ac8a-00e6449281b4.png)
</details>
&nbsp;

So for example, you can't find _American servers_ by searching for the `US` country code:
<details>
<summary><strong>View screenshot …</strong></summary>
&nbsp;

![firefox_bU56gSJtgx](https://user-images.githubusercontent.com/4764956/226533827-a6cbbe3e-24a2-412c-8f82-9c5931e11110.png)
</details>

&nbsp;
# Proposed solution

Instead of the current situation:
<details>
<summary><strong>View screenshot …</strong></summary>
&nbsp;

![firefox_qsv8xbkHjq](https://user-images.githubusercontent.com/4764956/226534345-5a15bf3d-0a69-4ba9-8cd6-4ea998dea1e5.png)
</details>
&nbsp;

I propose something like this:
<details>
<summary><strong>View screenshot …</strong></summary>
&nbsp;

![firefox_A8lDBGWvXZ](https://user-images.githubusercontent.com/4764956/226534463-a9578262-4337-4d60-9c14-547ae8cbdc97.png)

↬ Or `Matching|Corresponding|Related results`, instead of `Suggested`.
</details>
&nbsp;

> __Note__: I voluntarily took the example of the **United Kingdom** which must be able to be found both with `GB` (the official ISO country code) and `UK`. So each entry must be associated to a "main country code" and to possible "alternative country codes", I would say.

&nbsp;
# Alternative solution

Be able to search with either the two-letter _(e.g. `US`)_ or three-letter _(e.g. `USA`)_ ISO country code.

&nbsp;
&nbsp;
#### _======= Resources (lists) for official country codes =======_
- https://www.iban.com/country-codes
- https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes#Current_ISO_3166_country_codes
- https://countrycode.org/

**Comment by maximtop** [comment]
I think we can implement it.

**Comment by contribucious** [comment]
:wave: Maxim!

Great! Thank _you_! :relaxed:

**Comment by contribucious** [comment]
@tvinzz Thanks! [Simpler](https://github.com/AdguardTeam/AdGuardVPNExtension/commit/16f6ba75c42d7ee2ee4b95650c4e0ac8531f9802) version but that's nice too. 👍

Once the `Review` status is left, I assume that internally you will also reflect this change on [AdGuardVPNForWindows](https://github.com/AdguardTeam/AdGuardVPNForWindows)/[AdGuardVPNForMac](https://github.com/AdguardTeam/AdGuardVPNForMac) and on [AdGuardVPNForiOS](https://github.com/AdguardTeam/AdGuardVPNForiOS)/[AdGuardVPNForAndroid](https://github.com/AdguardTeam/AdGuardVPNForAndroid)? _(If not already OK on all of these products.)_

↪️ This will be very useful for the latter in the case of Android TV / Google TV (with a remote control): `united k` ➞ `gb` for example. 🙂

**Comment by maximtop** [comment]
> @tvinzz Thanks! [Simpler](https://github.com/AdguardTeam/AdGuardVPNExtension/commit/16f6ba75c42d7ee2ee4b95650c4e0ac8531f9802) version but that's nice too. 👍
> 
> Once the `Review` status is left, I assume that internally you will also reflect this change on [AdGuardVPNForWindows](https://github.com/AdguardTeam/AdGuardVPNForWindows)/[AdGuardVPNForMac](https://github.com/AdguardTeam/AdGuardVPNForMac) and on [AdGuardVPNForiOS](https://github.com/AdguardTeam/AdGuardVPNForiOS)/[AdGuardVPNForAndroid](https://github.com/AdguardTeam/AdGuardVPNForAndroid)? _(If not already OK on all of these products.)_
> 
> ↪️ This will be very useful for the latter in the case of Android TV / Google TV (with a remote control): `united k` ➞ `gb` for example. 🙂

@contribucious You might want to create issues in the relevant repositories that refer to this issue.

**Comment by contribucious** [comment]
@maximtop _Done_. :relaxed:
