### ISSUE TITLE
Last endpoint is not visible during scrolling

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/AdGuardVPNExtension#88]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

1.4.14

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
```

### Issue Details

The last endpoint is not visible during scrolling.

### Expected Behavior

The last endpoint is visible while scrolling to the end.

**Comment by shark696969** [comment]
Closed for all

Pada tanggal Jum, 31 Mar 2023 23.11, Maxim Topciu ***@***.***>
menulis:

**Comment by gork7777** [comment]
Relates to https://github.com/AdguardTeam/AdGuardVPNExtension/issues/87
