### ISSUE TITLE
Doesn't detect most items when pressing TAB button

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNExtension#89]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

Beta 1.4.20

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome v112.0.5615.121
```

### Issue Details

The AG Browser extension detects important items (links, search, drop-down menus, option buttons, filter) when you press the `TAB` button and the item is selected as if you hovered the mouse cursor over it. But many things are not selected in VPN.

### Expected Behavior

Important items (I'll explain below) should be selected when pressing the `TAB` button.

- Settings tab: Drop-down menus, `Block WebRTC`, `Help us improve`, `Add AdGuard VPN item to the browser’s context menu`, `DNS server` (Popular DNS server lists and add custom DNS server button should also be selected) options should be selected.

- Exclusion tab: `Actions` drop-down, `Add a website` (In the `From the list` tab, group lists should be selected.) options should be selected. But if you any select group from the list, TAB doesn't detect add button. options should be selected.

- Support tab: `FAQ`, `Report a bug` (`Include diagnostic report in message` button too), `Leave a feedback` options should be selected. 

- Free GBs tab: `Invite your friend`, `Confirm your email`, `Add another device` options should be selected. 

### Screenshots

<details><summary>Settings tab:</summary>

https://user-images.githubusercontent.com/35523759/232245419-46162ad9-25aa-47ed-bfcc-9d68319c307a.mp4
</details>

<details><summary>Exclusion tab:</summary>

https://user-images.githubusercontent.com/35523759/232245440-8a53973a-6d09-49a4-bac5-8d9c7137bea8.mp4
</details>

<details><summary>Support tab:</summary>

https://user-images.githubusercontent.com/35523759/232245451-f32b5e06-72ad-4437-9c48-5418d23e7c55.mp4
</details>

<details><summary>Free GBs tab:</summary>

https://user-images.githubusercontent.com/35523759/232245459-1e4cd298-53eb-49a9-8b0a-7d4bdf774fe2.mp4
</details>

**Comment by gork7777** [comment]
Bonus! `TAB` button doesn't work in extension UI too.

<details><summary>Interface</summary>

https://github.com/AdguardTeam/AdGuardVPNExtension/assets/35523759/caab98e2-54fc-4a1e-b9cc-cb874dcf178e
</details>

**Comment by slavaleleka** [comment]
here is a record of location selection by Tab (+ Enter) — looks like it works but the selected element is not highlighted:
https://uploads.adguard.org/slbdzdrvvyrty.mp4

**Comment by gork7777** [comment]
@slavaleleka Yes, that's why I reported it.
