### ISSUE TITLE
Firewall - disable firewall blocking notifications

### ISSUE THREAD

**Issue by sconim** [AdguardTeam/AdGuardVPNExtension#94]
### Issue Details

When the firewall generates a notification indicating that a certain app was blocked (by firewall), there is no way to prevent that specific notification from repeating. 

### Proposed solution

Similarly to the previous version, add a toggle (each app) that would permanently disabled further notifications related to the firewall blocking the app. 

### Alternative solution

Repeated block notifications become a nuisance, especially when the user's intention was to permanently block certain apps.

**Comment by zzebrum** [comment]
@sconim are you talking about AdGuard for android v4.0 nightly?

**Comment by sconim** [comment]
Yes, I was referring to AdGuard 4.0 Beta for Android but it seems I'm in the wrong repository, so I'll just close the ticket.
