### ISSUE TITLE
Free traffic accounting issue

### ISSUE THREAD

**Issue by Anizam** [AdguardTeam/AdGuardVPNExtension#97]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN Browser Extension version

1.4.20

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome 113.0.5672.127 (64 bit)
```

### Issue Details

Free traffic is charged on sites where the extension has been disabled (youtube in my case). The speed limit is also applied when the traffic limit is reached. So, you constantly have to check whether extension is enabled or not.

### Expected Behavior

When i disable VPN on this site, i expect it should be fully disabled on this site

**Comment by Anizam** [comment]
Yes, only one was checked
![image](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/28562958/13465523-09e4-470f-b517-c59f65e209bd)
So, it means this is a UX problem.
When i click "Disable VPN for this website" button, i expect all the checkboxes to be checked by default
![image](https://github.com/AdguardTeam/AdGuardVPNExtension/assets/28562958/9f53a59c-8e7f-4b0e-9b88-dd552cfa03af)
Also when i click "Reset to default" button, all checkboxes become selected (as expected)

**Comment by alexx7311** [comment]
Hello! Especially for this case there is an option to add a website from the list. We don't plan to change the logic of exceptions yet.
